In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from bs4 import BeautifulSoup as BS
import requests as rs

In [40]:
#Collecting Data from GitHub API & Converting the Data into a DataFrame
URL = "https://api.github.com/search/repositories?q=machine+learning&sort=stars&order=desc&per_page=100"
response = rs.get(URL)
data = response.json()
Adf = pd.DataFrame(data["items"])
#Selecting the Required Columns
df=Adf[[
"name",
"owner",
"language",
"stargazers_count",
"forks_count",
"watchers_count",
"open_issues_count",
"created_at",
"updated_at",
"license"
]]

#**From Here,Cleaning & Exploring the Data started...**
During Prepration, the following will be performed:


Extracting the warehouse owner's username from the Owner column.

Extracting the license name from the License column.

Resolving missing values.

Deleting duplicate records.

Converting the creation date and update date to DateTime.

Renaming columns for easier use in SQL.

Formating and organizing text.

In [41]:
df.columns = df.columns.str.lower().str.strip()
print("Final DataFrame Shape:", df.shape)

Final DataFrame Shape: (100, 10)

In [42]:
df.head()

,name,owner,language,stargazers_count,forks_count,watchers_count,open_issues_count,created_at,updated_at,license
0,tensorflow,"{'login': 'tensorflow', 'id': 15658638, 'node_...",C++,196930,75948,196930,2862,2015-11-07T01:19:20Z,2026-08-09T00:15:15Z,"{'key': 'apache-2.0', 'name': 'Apache License ..."
1,transformers,"{'login': 'huggingface', 'id': 25720743, 'node...",Python,163478,34147,163478,2359,2018-10-29T13:56:00Z,2026-08-08T23:52:58Z,"{'key': 'apache-2.0', 'name': 'Apache License ..."
2,ML-For-Beginners,"{'login': 'microsoft', 'id': 6154722, 'node_id...",Jupyter Notebook,89164,21860,89164,8,2021-03-03T01:34:05Z,2026-08-09T01:10:11Z,"{'key': 'mit', 'name': 'MIT License', 'spdx_id..."
3,funNLP,"{'login': 'fighting41love', 'id': 11475294, 'n...",Python,82345,15271,82345,52,2018-08-21T11:20:39Z,2026-08-08T20:33:27Z,None
4,awesome-machine-learning,"{'login': 'josephmisiti', 'id': 246302, 'node_...",Python,73956,15603,73956,22,2014-07-15T19:11:19Z,2026-08-08T23:40:53Z,"{'key': 'other', 'name': 'Other', 'spdx_id': '..."

In [43]:
df["created_at"]=pd.to_datetime(df["created_at"])
df["updated_at"]=pd.to_datetime(df["updated_at"])
owner_names = pd.DataFrame([item["owner"]["login"] for item in data["items"] if isinstance(item.get("owner"), dict)], columns=["username"])

license_names = pd.DataFrame([item["license"]["name"] for item in data["items"] if isinstance(item.get("license"), dict)], columns=["license_name"])

resdf = pd.concat([owner_names, license_names], axis=1)
df["owner"]=resdf["username"]
df["license"]=resdf["license_name"]

df = df.drop_duplicates()

/tmp/ipykernel_548/3354971030.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["created_at"]=pd.to_datetime(df["created_at"])
/tmp/ipykernel_548/3354971030.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["updated_at"]=pd.to_datetime(df["updated_at"])
/tmp/ipykernel_548/3354971030.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["owner"]=resdf["username"]
/tmp/ipykernel_548/3354971030.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["license"]=resdf["license_name"]

In [44]:
df.shape

(100, 10)

In [45]:
df.head()

,name,owner,language,stargazers_count,forks_count,watchers_count,open_issues_count,created_at,updated_at,license
0,tensorflow,tensorflow,C++,196930,75948,196930,2862,2015-11-07 01:19:20+00:00,2026-08-09 00:15:15+00:00,Apache License 2.0
1,transformers,huggingface,Python,163478,34147,163478,2359,2018-10-29 13:56:00+00:00,2026-08-08 23:52:58+00:00,Apache License 2.0
2,ML-For-Beginners,microsoft,Jupyter Notebook,89164,21860,89164,8,2021-03-03 01:34:05+00:00,2026-08-09 01:10:11+00:00,MIT License
3,funNLP,fighting41love,Python,82345,15271,82345,52,2018-08-21 11:20:39+00:00,2026-08-08 20:33:27+00:00,Other
4,awesome-machine-learning,josephmisiti,Python,73956,15603,73956,22,2014-07-15 19:11:19+00:00,2026-08-08 23:40:53+00:00,"BSD 3-Clause ""New"" or ""Revised"" License"

In [46]:
df.isnull().sum()

name                  0
owner                 0
language             23
stargazers_count      0
forks_count           0
watchers_count        0
open_issues_count     0
created_at            0
updated_at            0
license              22
dtype: int64

In [47]:
df=df.dropna()

In [48]:
df.shape

(60, 10)

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 60 entries, 0 to 77
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   name               60 non-null     object
 1   owner              60 non-null     object
 2   language           60 non-null     object
 3   stargazers_count   60 non-null     int64
 4   forks_count        60 non-null     int64
 5   watchers_count     60 non-null     int64
 6   open_issues_count  60 non-null     int64
 7   created_at         60 non-null     datetime64[ns, UTC]
 8   updated_at         60 non-null     datetime64[ns, UTC]
 9   license            60 non-null     object
dtypes: datetime64[ns, UTC](2), int64(4), object(4)
memory usage: 5.2+ KB

In [50]:
df.describe()

       stargazers_count   forks_count  watchers_count  open_issues_count
count         60.000000     60.000000       60.000000          60.000000
mean       26284.866667   6273.833333    26284.866667         371.016667
std        33663.456363  11011.393506    33663.456363         642.324974
min         9058.000000    696.000000     9058.000000           2.000000
25%        11161.000000   1842.250000    11161.000000          20.250000
50%        14702.000000   3535.000000    14702.000000          84.500000
75%        22745.000000   5113.000000    22745.000000         400.750000
max       196930.000000  75948.000000   196930.000000        2862.000000

In [51]:
numeric_df = df.select_dtypes(include='number')
gap = numeric_df.max() - numeric_df.min()
print(gap)

stargazers_count     187872
forks_count           75252
watchers_count       187872
open_issues_count      2860
dtype: int64

In [52]:
df=df.rename(columns={"stargazers_count"	: "stargazers" ,"forks_count"	: "forks" ,"watchers_count"	: "watchers" ,"open_issues_count" : "open_issues","created_at" : "creation","updated_at" : "updating" })

df['name'] = df['name'].str.lower().str.strip()
df['owner'] = df['owner'].str.lower().str.strip()
df['language'] = df['language'].str.strip()
df['license'] = df['license'].str.lower().str.strip()

In [53]:
'''When I Explored the head of the Data,I found that someone Entired Jupyter Notebook
 (a platform usually used for Python Coding);so I fixed that.'''
df.groupby(by="language").size()

language
C                    1
C#                   2
C++                 11
Go                   2
HTML                 2
Java                 1
JavaScript           3
Jupyter Notebook    13
Python              24
Scala                1
dtype: int64

In [54]:
df['language'] = df['language'].replace('Jupyter Notebook', 'Python')

In [55]:
df.groupby(by="language").size()

language
C              1
C#             2
C++           11
Go             2
HTML           2
Java           1
JavaScript     3
Python        37
Scala          1
dtype: int64

In [56]:
df.head()

,name,owner,language,stargazers,forks,watchers,open_issues,creation,updating,license
0,tensorflow,tensorflow,C++,196930,75948,196930,2862,2015-11-07 01:19:20+00:00,2026-08-09 00:15:15+00:00,apache license 2.0
1,transformers,huggingface,Python,163478,34147,163478,2359,2018-10-29 13:56:00+00:00,2026-08-08 23:52:58+00:00,apache license 2.0
2,ml-for-beginners,microsoft,Python,89164,21860,89164,8,2021-03-03 01:34:05+00:00,2026-08-09 01:10:11+00:00,mit license
3,funnlp,fighting41love,Python,82345,15271,82345,52,2018-08-21 11:20:39+00:00,2026-08-08 20:33:27+00:00,other
4,awesome-machine-learning,josephmisiti,Python,73956,15603,73956,22,2014-07-15 19:11:19+00:00,2026-08-08 23:40:53+00:00,"bsd 3-clause ""new"" or ""revised"" license"

In [57]:
#Saving the Cleaned Data
df.to_csv("github_projects.csv",index=False)